name = "GBTM"
description = "Simplified Hugo theme. Based on the \"Poison\" theme."
min_version = "0.101.0"

[author]
    name = "Rokker Ruslan"

[original]
    author =  "Luke Orth"
    homepage = "http://markdotto.com/"
